Main script working via qsub, susing scratch space for generate fastq

diff --git a/assemble_flowcell b/assemble_flowcell
--- a/assemble_flowcell
+++ b/assemble_flowcell
@@ -1,5 +1,11 @@
 #!/bin/bash
 
+if ! [ -z "$JOB_ID" ]
+then
+	echo "This script cannot be used via qsub"
+	exit 1
+fi
+
 DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
 
 . $DIR/scripts/parse_args.sh
@@ -9,16 +15,12 @@ then
 	echo "Unable to make output directory"
 	usage
 fi
-
-if ! mkdir -p "$SCRATCH_DIR"
+if ! [ -f "$RUN_DIR/SampleSheet.csv" ]
 then
-	echo "Unable to create scratch dir: $SCRATCH_DIR"
+	echo "Run directory or sample sheet do not exist"
 	usage
 fi
 
-
-$DIR/generate_fastq -r "$RUN_DIR" -o "$OUT_DIR" && \
-	$DIR/assemble_samples -r "$RUN_DIR" -o "$OUT_DIR" 
-	#&& \
-	#$DIR/generate_metrics -r "$RUN_DIR" -o "$OUT_DIR" 
-rm -rf $SCRATCH_DIR
+echo $DIR/scripts/assemble_flowcell -r "$RUN_DIR" -o "$OUT_DIR" -s "$SCRATCH_ROOT" | \
+	qsub -pe threaded 16 -l 'h_vmem=96G' -cwd -N assemble_flowcell -e assemble_flowcell.err \
+	-o assemble_flowcell.out -m es -M $USER@illumina.com
diff --git a/scripts/assemble_samples b/scripts/assemble_samples
--- a/scripts/assemble_samples
+++ b/scripts/assemble_samples
@@ -1,7 +1,6 @@
 #!/bin/bash
 
-DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
-
+DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )
 . $DIR/scripts/parse_args.sh
 . $DIR/scripts/parallel_utils.sh
 
@@ -27,12 +26,12 @@ SPADES_OUTPUT_ROOT=$SCRATCH_DIR/spades
 
 # FASTQs are only read once - no need to stage to scratch if not already there
 # but if the ARE there, reading them will be faster than Isilon
-if ls $SCRATCH_DIR/Fastq/*.fastq.gz &> /dev/null
+if ls $SCRATCH_DIR/Fastq/Fastq/*.fastq.gz &> /dev/null
 then
-	FASTQ_DIR=$SCRATCH_DIR/Fastq
-elif ls $OUT_DIR/Fastq/*.fastq.gz &> /dev/null
+	FASTQ_DIR=$SCRATCH_DIR/Fastq/Fastq
+elif ls $OUT_DIR/Fastq/Fastq/*.fastq.gz &> /dev/null
 then
-	FASTQ_DIR=$OUT_DIR/Fastq
+	FASTQ_DIR=$OUT_DIR/Fastq/Fastq
 else
 	echo "No FASTQ files found"
 	exit 1
@@ -56,9 +55,9 @@ fi
 if ! [ -z "$JOB_ID" ]
 then
 	# Running as an SGE_JOB
-	if ! rsync -avpP $SPADES_OUTPUT_ROOT $OUT_DIR/spades
+	if ! rsync -avpP $SPADES_OUTPUT_ROOT/ $OUT_DIR/spades
 	then
-		echo "Error syncing spades results to to output"
+		echo "Error syncing spades results to output"
 		exit 1
 	fi
 else
