Make downsampling & read trimming parameterizable

diff --git a/scripts/assemble_flowcell b/scripts/assemble_flowcell
--- a/scripts/assemble_flowcell
+++ b/scripts/assemble_flowcell
@@ -15,25 +15,31 @@ then
 	usage
 fi
 
+
 FAILURES=false
 
-if !  $DIR/scripts/align_samples -r "$RUN_DIR" -o "$OUT_DIR" -s "$SCRATCH_ROOT"
+if !  $DIR/scripts/align_samples ${ALL_ARGS[@]}
 then
 	echo "align_samples failed!"
 	FAILURES=true
 fi
-if !  $DIR/scripts/downsample_fastqs -r "$RUN_DIR" -o "$OUT_DIR" -s "$SCRATCH_ROOT"
+
+if ! [ -z "$DEPTH" ]
 then
-	echo "downsample_fastqs failed!"
-	FAILURES=true
+	if !  $DIR/scripts/downsample_fastqs ${ALL_ARGS[@]}
+	then
+		echo "downsample_fastqs failed!"
+		FAILURES=true
+	fi
 fi
 
-if ! $DIR/scripts/assemble_samples -r "$RUN_DIR" -o "$OUT_DIR" -s "$SCRATCH_ROOT" 
+
+if ! $DIR/scripts/assemble_samples ${ALL_ARGS[@]}
 then
 	echo "assemble_samples failed!"
 	FAILURES=true
 fi
-if ! $DIR/scripts/generate_all_metrics -r "$RUN_DIR" -o "$OUT_DIR" -s "$SCRATCH_ROOT" $OUT_DIR/spades
+if ! $DIR/scripts/generate_all_metrics ${ALL_ARGS[@]} $OUT_DIR/spades
 then
 	echo "generate_all_metrics failed!"
 	FAILURES=true
diff --git a/scripts/downsample_fastqs b/scripts/downsample_fastqs
--- a/scripts/downsample_fastqs
+++ b/scripts/downsample_fastqs
@@ -3,7 +3,13 @@
 DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )
 . $DIR/scripts/parse_args.sh
 . $DIR/scripts/tool_paths.sh
-TARGET_COVERAGE=70
+
+if [ -z "$DEPTH" ] 
+then
+	echo "DEPTH is required for this script"
+	exit 1
+fi
+
 
 if ! mkdir -p "$SCRATCH_DIR"
 then
@@ -54,7 +60,7 @@ for sample in $SAMPLES
 do
 	# find the coverage
 	coverage=$(grep "Mean coverage" $LOCAL_ALIGN_DIR/${sample}*summary.csv | cut -f2 -d,)
-	ratio=$(echo "scale=3; $TARGET_COVERAGE / $coverage" | bc)
+	ratio=$(echo "scale=3; $DEPTH / $coverage" | bc)
 	if [ $(echo "$ratio > 1.0" | bc -l) -eq 1 ]
 	then
 		echo "COPYING fastq files"
