Downsample Fastqs to 70 mean, go parallel

diff --git a/scripts/assemble_flowcell b/scripts/assemble_flowcell
--- a/scripts/assemble_flowcell
+++ b/scripts/assemble_flowcell
@@ -22,6 +22,11 @@ then
 	echo "align_samples failed!"
 	FAILURES=true
 fi
+if !  $DIR/scripts/downsample_fastqs -r "$RUN_DIR" -o "$OUT_DIR" -s "$SCRATCH_ROOT"
+then
+	echo "downsample_fastqs failed!"
+	FAILURES=true
+fi
 
 if ! $DIR/scripts/assemble_samples -r "$RUN_DIR" -o "$OUT_DIR" -s "$SCRATCH_ROOT" 
 then
diff --git a/scripts/assemble_samples b/scripts/assemble_samples
--- a/scripts/assemble_samples
+++ b/scripts/assemble_samples
@@ -34,12 +34,12 @@ SPADES_OUTPUT_ROOT=$SCRATCH_DIR/spades
 
 # FASTQs are only read once - no need to stage to scratch if not already there
 # but if the ARE there, reading them will be faster than Isilon
-if ls $SCRATCH_DIR/Alignment/Fastq/*.fastq.gz &> /dev/null
+if ls $SCRATCH_DIR/Fastq/*.fastq.gz &> /dev/null
 then
-	FASTQ_DIR=$SCRATCH_DIR/Alignment/Fastq
-elif ls $OUT_DIR/Alignment/Fastq/*.fastq.gz &> /dev/null
+	FASTQ_DIR=$SCRATCH_DIR/Fastq
+elif ls $OUT_DIR/Fastq/*.fastq.gz &> /dev/null
 then
-	FASTQ_DIR=$OUT_DIR/Alignment/Fastq
+	FASTQ_DIR=$OUT_DIR/Fastq
 else
 	echo "No FASTQ files found"
 	exit 1
@@ -49,10 +49,18 @@ SAMPLES=$(cd $FASTQ_DIR && ls *.fastq.gz | cut -f1 -d_ | sort -u | grep -v Undet
 for sample in $SAMPLES
 do
 	echo "Processing sample $sample"
-	$DIR/scripts/assemble_sample -r "$RUN_DIR" -o "$SPADES_OUTPUT_ROOT/$sample" $(find $FASTQ_DIR -name "$sample*fastq.gz" -print) -t 12 -m 96
+	$DIR/scripts/assemble_sample -r "$RUN_DIR" -o "$SPADES_OUTPUT_ROOT/$sample" $(find $FASTQ_DIR -name "$sample*fastq.gz" -print) -t 4 -m 32 &
+	jobs="$jobs $!"
+ 	wait_until_jobs_below 3
 done
 
 failed=false
+
+if ! wait_until_all_complete $jobs
+then
+	failed=true
+	echo "Error assembling one or more samples"
+fi
 
 if ! [ -z "$JOB_ID" ]
 then
