Add picard metrics, fix alignment

diff --git a/scripts/assemble_flowcell b/scripts/assemble_flowcell
--- a/scripts/assemble_flowcell
+++ b/scripts/assemble_flowcell
@@ -15,8 +15,28 @@ then
 	usage
 fi
 
+FAILURES=false
 
-$DIR/scripts/align_samples -r "$RUN_DIR" -o "$OUT_DIR" -s "$SCRATCH_ROOT" && \
-	$DIR/scripts/assemble_samples -r "$RUN_DIR" -o "$OUT_DIR" -s "$SCRATCH_ROOT" && \
-	$DIR/scripts/generate_all_metrics -r "$RUN_DIR" -o "$OUT_DIR" -s "$SCRATCH_ROOT" $OUT_DIR/spades && \
+if !  $DIR/scripts/align_samples -r "$RUN_DIR" -o "$OUT_DIR" -s "$SCRATCH_ROOT"
+then
+	echo "align_samples failed!"
+	FAILURES=true
+fi
+
+if ! $DIR/scripts/assemble_samples -r "$RUN_DIR" -o "$OUT_DIR" -s "$SCRATCH_ROOT" 
+then
+	echo "assemble_samples failed!"
+	FAILURES=true
+fi
+if ! $DIR/scripts/generate_all_metrics -r "$RUN_DIR" -o "$OUT_DIR" -s "$SCRATCH_ROOT" $OUT_DIR/spades
+then
+	echo "generate_all_metrics failed!"
+	FAILURES=true
+fi
 rm -rf $SCRATCH_DIR
+
+if $FAILURES
+then
+	echo "FAILURES OCCURRED! Look at the logs and figure out why"
+	exit 1
+fi
diff --git a/scripts/generate_metrics b/scripts/generate_metrics
--- a/scripts/generate_metrics
+++ b/scripts/generate_metrics
@@ -40,9 +40,24 @@ shift 2
 export PATH=/illumina/thirdparty/quast-2.3:/illumina/thirdparty/python/python-2.7.8/bin:$PATH
 export PYTHONPATH=/illumina/thirdparty/python/python_libraries/packages:$PYTHONPATH
 
+failed=false
 
 if ! quast.py --debug --scaffolds -o "$OUT_DIR" -R "$GENOME" "$ASSEMBLY/scaffolds.fasta"
 then
 	echo "Quast failed"
+	failed=true
+fi
+
+BAM_FILE=$(ls $OUT_DIR/Alignment/$ASSEMBLY*bam)
+
+if ! java -Xmx4g -jar /illumina/thirdparty/picard-tools/picard-tools-1.85/CollectMultipleMetrics.jar INPUT=$BAM_FILE OUTPUT=$OUT_DIR/picard/$ASSEMBLY/metrics REFERENCE_SEQUENCE=$GENOME
+then
+	failed=true
+	echo "Picard failed!"
+fi
+
+
+if $failed
+then
 	exit 1
 fi
