Refactor - add reporting

diff --git a/scripts/generate_all_metrics b/scripts/generate_all_metrics
--- a/scripts/generate_all_metrics
+++ b/scripts/generate_all_metrics
@@ -49,12 +49,18 @@ do
 		echo "Error generating picard metrics for $sample"
 		failed=true
 	fi
-	if ! $DIR/scripts/align_assembly_to_reference -r "$RUN_DIR" -o "$OUT_DIR/last/$sample" $SPADES_OUTPUT_ROOT/$sample $GENOME
+	if ! $DIR/scripts/generate_visualizations -r "$RUN_DIR" -o "$OUT_DIR/visualization/$sample" $SPADES_OUTPUT_ROOT/$sample $GENOME
 	then
-		echo "Error generating LAST alignment for $sample"
+		echo "Error generating visualizations for $sample"
 		failed=true
 	fi
 done
+
+if ! $DIR/scripts/generate_summary_report -r "$RUN_DIR" -o "$OUT_DIR" > $OUT_DIR/summary.html
+then
+	echo "Error generating summary report"
+	failed=true
+fi
 
 
 if $failed
